spring:
  application:
    name: mmall-seller-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://192.168.100.209:3306/mmallseller?useUnicode=true&characterEncoding=utf8              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.keerte.boot.mmall.seller.common.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: mmall-seller-server8001
  client:
    service-url:
      defaultZone: http://mmall-eureka-server7981:7981/eureka
